import { StyleSheet, View } from "react-native";
import { Colors } from "../context/colors/Colors";

export const HomeStyle = StyleSheet.create({
    view:{
        width:'100%',
        height:'100%',
        backgroundColor:Colors.grisAzulado,
        alignItems:'center'
    },
    header:{
        height:200,
        width:'100%',
        backgroundColor:Colors.negroClaro,
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
        position:'relative',
        alignItems:'center',
        justifyContent:'flex-start',
        paddingTop:20
    },
    textHeader:{
        fontSize:22,
        color:Colors.gris,
        fontWeight:'800',
        textAlign:'center',
        width:'60%'
    },
    headerView:{
        position:'absolute',
        height:200,
        width:'90%',
        backgroundColor:'black',
        top:110,
        borderRadius:20,
        overflow:'hidden',
        flexDirection:'row'
    },
    headerViewSection:{
        height:'100%',
        width:'50%',
        alignItems:'flex-start',
        justifyContent:'center',
        gap:5,
        overflow:'hidden'
    },
    headerViewTittle:{
        fontSize:25,
        color:Colors.gris,
        fontWeight:'800',
        paddingRight:10,
        paddingLeft:10,
        width:'70%',
        textAlign:'left',
    },
    headerViewSubTittle:{
        fontSize:18,
        color:Colors.gris,
        fontWeight:'500',
        paddingLeft:10,
        paddingRight:10,
        textAlign:'left'
    },

    //Categorias
    Category:{
        flex:1,
        height:100,
        width:'100%',
        alignItems:'center',
        justifyContent:'center',

        marginTop:130
    },
    textCategory:{
        fontSize:20,
        color:Colors.morado,
        fontWeight:'700',
        textAlign:'left',
        width:'100%',
        paddingLeft:20
    },
    containerCategory:{
        flex:1,
        width:'90%',
        paddingBottom:10,
        paddingTop:10,
        gap:10,
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'flex-start',
        minWidth:380,
        paddingLeft:12,
        paddingBottom:30
    }
})